//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeSpokedDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class discount
    {
        public int id { get; set; }
        public int product_id { get; set; }
        public System.DateTime begin_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public decimal discount1 { get; set; }
    
        public virtual product product { get; set; }
    }
}
